"""Keep autogenerated ops in dependency order across fork-managed objects and
stock table changes.

Background
----------
On Alembic >= 1.18 the schema-level comparators run through a
``PriorityDispatcher``. ``AutogenContext`` branches the *global* comparator
registry — where this library installs its ``@comparators.dispatch_for("schema")``
functions (``compare_registered_entities``, ``compare_indexes``,
``compare_check_constraints``) — *before* Alembic merges in its built-in table
comparator. All of them register at the default ``MEDIUM`` priority, and within a
priority the dispatch order is insertion order, so the fork's comparators end up
running *before* the built-in table diff. Every comparator does
``upgrade_ops.ops.append(...)``, so the fork's create ops land in
``upgrade_ops.ops`` ahead of ``CreateTableOp`` and the generated migration tries
to create a trigger / function / index before the table it depends on.

Additionally, within the fork's own comparators, ``compare_indexes`` and
``compare_check_constraints`` are registered (via ``__init__.py`` imports) before
``compare_registered_entities`` (registered when a ``ReplaceableEntity`` subclass
is first imported). This means ``CreateIndexOp`` and ``CreateCheckConstraintOp``
land in ``upgrade_ops.ops`` before ``CreateOp`` / ``ReplaceOp``, so naively
preserving relative order within a single creates bucket would place indexes and
constraints before the entities they depend on.

(Before Alembic 1.18 the built-in comparators registered onto the shared
dispatcher first, so creates were already ordered correctly — the bug is specific
to the priority dispatcher, hence the version guard below.)

Fix
---
Register a ``LAST``-priority ``"schema"`` comparator. It runs after every
``MEDIUM`` comparator (the built-in table diff included) and rewrites
``upgrade_ops.ops`` as ``[library enum ops, library drops, stock ops, library
entity creates, library index/constraint creates]``:

* library **enum ops** move ahead of everything → an enum type and its labels
  exist before any column, default, or entity that references them. Their
  relative order is preserved, which matters: ``pg_enum`` plans a run of
  ``ADD VALUE`` statements whose anchors depend on the preceding ones landing
  first.
* library **drops** move before all stock ops → dependents are dropped before the
  tables they hang off of.
* library **entity creates** (views, functions, triggers, etc.) move after all
  stock ops → tables/columns exist before the entities that depend on them.
* library **index/constraint creates** move after entity creates → entities exist
  before the indexes and constraints that depend on them (upgrade correctness).

Downgrade is produced by ``upgrade_ops.reverse_into(downgrade_ops)`` *after* this
comparator runs, so reordering the upgrade list makes both directions correct.
The relative order within each group is preserved (entities keep the order
``solve_resolution_order`` chose; stock keeps Alembic's FK-aware order).
"""
from __future__ import annotations

from alembic.autogenerate import comparators
from alembic.autogenerate.api import AutogenContext
from alembic.operations import MigrateOperation, ops

from alembic_utils_extended.pg_enum_ops import AddEnumValueOp, CreateEnumTypeOp
from alembic_utils_extended.reversible_op import CreateOp, DropOp, ReplaceOp

try:
    # ``DispatchPriority`` / the priority dispatcher are new in Alembic 1.18.
    from alembic.util.langhelpers import DispatchPriority
except ImportError:  # pragma: no cover - Alembic < 1.18 orders creates correctly already
    DispatchPriority = None

_LIBRARY_ENUM_OPS = (CreateEnumTypeOp, AddEnumValueOp)
_LIBRARY_ENTITY_CREATE_OPS = (CreateOp, ReplaceOp)
_LIBRARY_INDEX_CONSTRAINT_CREATE_OPS = (ops.CreateIndexOp, ops.CreateCheckConstraintOp)
_LIBRARY_DROP_OPS = (DropOp, ops.DropIndexOp, ops.DropConstraintOp)


def reorder_upgrade_ops(upgrade_ops: ops.UpgradeOps) -> None:
    """Rewrite ``upgrade_ops.ops`` to
    ``[library enum ops, library drops, stock ops, library entity creates, library index/constraint creates]``."""
    enum_ops: list[MigrateOperation] = []
    drops: list[MigrateOperation] = []
    stock: list[MigrateOperation] = []
    entity_creates: list[MigrateOperation] = []
    index_creates: list[MigrateOperation] = []
    for op in upgrade_ops.ops:
        if isinstance(op, _LIBRARY_ENUM_OPS):
            enum_ops.append(op)
        elif isinstance(op, _LIBRARY_DROP_OPS):
            drops.append(op)
        elif isinstance(op, _LIBRARY_ENTITY_CREATE_OPS):
            entity_creates.append(op)
        elif isinstance(op, _LIBRARY_INDEX_CONSTRAINT_CREATE_OPS):
            index_creates.append(op)
        else:
            stock.append(op)
    upgrade_ops.ops[:] = enum_ops + drops + stock + entity_creates + index_creates


if DispatchPriority is not None:

    @comparators.dispatch_for("schema", priority=DispatchPriority.LAST)
    def reorder_library_ops(
        _autogen_context: AutogenContext,
        upgrade_ops: ops.UpgradeOps,
        _schemas: list[str | None],
    ) -> None:
        """Runs after all MEDIUM comparators; see the module docstring."""
        reorder_upgrade_ops(upgrade_ops)
